version: '3.7'
services:
  prod:
    image: tomcat:8-alpine
    restart: on-failure:3
    ports:
      - '8080:8080'
    volumes:
      - webapps:/usr/local/tomcat/webapps

  build:
    depends_on:
      - prod  # Presumably Docker prepopulates volumes with the existing contents
              # as stated here: https://docs.docker.com/engine/storage/volumes/#populate-a-volume-using-a-container
    context: .
    dockerfile: build.Dockerfile
    volumes:
      - webapps:/tmp/hello

volumes:
  webapps:



